### ISSUE TITLE
Better error messages if the fetch request fails

### ISSUE THREAD

**Issue by loganwilliams** [bellingcat/tiktok-timestamp#1]

**Comment by Ollie-Boyd** [comment]
Hey @loganwilliams , I can do that no probs. Do you have an example URL that fails or any more details? Cheers!

**Comment by Ollie-Boyd** [comment]
@loganwilliams fixed with PR https://github.com/bellingcat/tiktok-timestamp/pull/2 . Please let me know if there's any more projects to work on 🙂

**Comment by loganwilliams** [comment]
@Ollie-Boyd Hey Ollie, thanks for the contribution! I think it should still be possible to extract the timestamp from the metadata by looking for the `createTime` attribute, but that seems perhaps unnecessary given the video ID trick here.
